spring.application.name=ecommerce-api

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# JWT Configuration
jwt.secret=************
jwt.expiration=86400000

paystack.secret-key=sk_test_******
paystack.base-url=https://api.paystack.co